# 01. Data Cleaning

## Importing libraries and datasets

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
df1 = pd.read_csv("utahjazz24-25stats.csv")

In [ ]:
df1.head()

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1,Keyonte George,21,PG,67,35.0,31.5,5.4,13.7,0.391,...,0.4,3.4,3.8,5.6,0.7,0.1,2.7,1.7,16.8,NaN
1,2,Lauri Markkanen,27,PF,47,47.0,31.4,6.3,14.9,0.423,...,1.5,4.4,5.9,1.5,0.7,0.4,1.4,1.7,19.0,NaN
2,3,John Collins,27,PF,40,31.0,30.5,7.0,13.3,0.527,...,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0,NaN
3,4,Walker Kessler,23,C,58,58.0,30.0,4.8,7.2,0.663,...,4.6,7.6,12.2,1.7,0.6,2.4,1.5,2.2,11.1,NaN
4,5,Collin Sexton,26,SG,63,61.0,27.9,6.6,13.8,0.480,...,1.0,1.8,2.7,4.2,0.7,0.1,2.5,2.3,18.4,NaN

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      20 non-null     int64
 1   Player  20 non-null     object
 2   Age     20 non-null     int64
 3   Pos     20 non-null     object
 4   G       20 non-null     int64
 5   GS      19 non-null     float64
 6   MP      20 non-null     float64
 7   FG      20 non-null     float64
 8   FGA     20 non-null     float64
 9   FG%     20 non-null     float64
 10  3P      20 non-null     float64
 11  3PA     20 non-null     float64
 12  3P%     19 non-null     float64
 13  2P      20 non-null     float64
 14  2PA     20 non-null     float64
 15  2P%     20 non-null     float64
 16  eFG%    20 non-null     float64
 17  FT      20 non-null     float64
 18  FTA     20 non-null     float64
 19  FT%     20 non-null     float64
 20  ORB     20 non-null     float64
 21  DRB     20 non-null     float64
 22  TRB     20 non-null     float64
 23  AST     20 non-null     float64
 24  STL     20 non-null     float64
 25  BLK     20 non-null     float64
 26  TOV     20 non-null     float64
 27  PF      20 non-null     float64
 28  PTS     20 non-null     float64
 29  Awards  0 non-null      float64
dtypes: float64(25), int64(3), object(2)
memory usage: 4.8+ KB

In [ ]:
df1.drop(columns=["Rk", "Awards"], inplace=True)

In [ ]:
df1.head()

,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Keyonte George,21,PG,67,35.0,31.5,5.4,13.7,0.391,2.6,...,0.818,0.4,3.4,3.8,5.6,0.7,0.1,2.7,1.7,16.8
1,Lauri Markkanen,27,PF,47,47.0,31.4,6.3,14.9,0.423,2.9,...,0.876,1.5,4.4,5.9,1.5,0.7,0.4,1.4,1.7,19.0
2,John Collins,27,PF,40,31.0,30.5,7.0,13.3,0.527,1.5,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Walker Kessler,23,C,58,58.0,30.0,4.8,7.2,0.663,0.1,...,0.520,4.6,7.6,12.2,1.7,0.6,2.4,1.5,2.2,11.1
4,Collin Sexton,26,SG,63,61.0,27.9,6.6,13.8,0.480,1.7,...,0.865,1.0,1.8,2.7,4.2,0.7,0.1,2.5,2.3,18.4

In [ ]:
df2 = pd.read_csv("utahjazz24-25players.csv")

In [ ]:
df2.head()

   No           Player Pos    Ht   Wt         Birth_Date Exp         College
0   0  Jordan Clarkson  SG   6-3  194        June 7 1992  10  Tulsa Missouri
1  13   Isaiah Collier  PG   6-3  210     October 8 2004   R             USC
2  20     John Collins  PF   6-9  235  September 23 1997   7     Wake Forest
3  15     Drew Eubanks   C   6-9  245    February 1 1997   6    Oregon State
4  22  Kyle Filipowski   C  6-11  250    November 7 2003   R            Duke

In [ ]:
df2.drop(columns=["No", "College"], inplace=True)

### Merging the two datasets

In [ ]:
df = pd.merge(df2, df1, on="Player", how="left")

In [ ]:
df.head()

,Player,Pos_x,Ht,Wt,Birth_Date,Exp,Age,Pos_y,G,GS,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Jordan Clarkson,SG,6-3,194,June 7 1992,10,32.0,SG,37.0,9.0,...,0.797,0.7,2.5,3.2,3.7,0.8,0.2,2.3,1.4,16.2
1,Isaiah Collier,PG,6-3,210,October 8 2004,R,20.0,PG,71.0,46.0,...,0.682,0.5,2.9,3.3,6.3,0.9,0.2,2.9,2.1,8.7
2,John Collins,PF,6-9,235,September 23 1997,7,27.0,PF,40.0,31.0,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Drew Eubanks,C,6-9,245,February 1 1997,6,27.0,C,37.0,4.0,...,0.632,1.1,3.5,4.5,1.2,0.3,0.9,0.8,1.2,5.8
4,Kyle Filipowski,C,6-11,250,November 7 2003,R,21.0,C,72.0,27.0,...,0.650,1.6,4.6,6.1,1.9,0.7,0.3,1.4,2.4,9.6

In [ ]:
df.rename(columns={"Ht":"Height"}, inplace=True)

In [ ]:
df.rename(columns={"Wt":"Weight"}, inplace=True)

In [ ]:
df.head()

,Player,Pos_x,Height,Weight,Birth_Date,Exp,Age,Pos_y,G,GS,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Jordan Clarkson,SG,6'3,194,June 7 1992,10,32.0,SG,37.0,9.0,...,0.797,0.7,2.5,3.2,3.7,0.8,0.2,2.3,1.4,16.2
1,Isaiah Collier,PG,6'3,210,October 8 2004,R,20.0,PG,71.0,46.0,...,0.682,0.5,2.9,3.3,6.3,0.9,0.2,2.9,2.1,8.7
2,John Collins,PF,6'9,235,September 23 1997,7,27.0,PF,40.0,31.0,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Drew Eubanks,C,6'9,245,February 1 1997,6,27.0,C,37.0,4.0,...,0.632,1.1,3.5,4.5,1.2,0.3,0.9,0.8,1.2,5.8
4,Kyle Filipowski,C,6'11,250,November 7 2003,R,21.0,C,72.0,27.0,...,0.650,1.6,4.6,6.1,1.9,0.7,0.3,1.4,2.4,9.6

## Data Cleaning

### Position column

In [ ]:
df.drop(columns=["Pos_y"], inplace=True)
df.rename(columns={"Pos_x":"Pos"}, inplace=True)

In [ ]:
df.head()

,Player,Pos,Height,Weight,Birth_Date,Exp,Age,G,GS,MP,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Jordan Clarkson,SG,6'3,194,June 7 1992,10,32.0,37.0,9.0,26.0,...,0.797,0.7,2.5,3.2,3.7,0.8,0.2,2.3,1.4,16.2
1,Isaiah Collier,PG,6'3,210,October 8 2004,R,20.0,71.0,46.0,25.9,...,0.682,0.5,2.9,3.3,6.3,0.9,0.2,2.9,2.1,8.7
2,John Collins,PF,6'9,235,September 23 1997,7,27.0,40.0,31.0,30.5,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Drew Eubanks,C,6'9,245,February 1 1997,6,27.0,37.0,4.0,15.4,...,0.632,1.1,3.5,4.5,1.2,0.3,0.9,0.8,1.2,5.8
4,Kyle Filipowski,C,6'11,250,November 7 2003,R,21.0,72.0,27.0,21.1,...,0.650,1.6,4.6,6.1,1.9,0.7,0.3,1.4,2.4,9.6

Birthdate column

In [ ]:
df["Birth_Date"] = pd.to_datetime(df["Birth_Date"])

In [ ]:
df.head()

,Player,Pos,Height,Weight,Birth_Date,Exp,Age,G,GS,MP,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Jordan Clarkson,SG,6'3,194,1992-06-07,10,32.0,37.0,9.0,26.0,...,0.797,0.7,2.5,3.2,3.7,0.8,0.2,2.3,1.4,16.2
1,Isaiah Collier,PG,6'3,210,2004-10-08,R,20.0,71.0,46.0,25.9,...,0.682,0.5,2.9,3.3,6.3,0.9,0.2,2.9,2.1,8.7
2,John Collins,PF,6'9,235,1997-09-23,7,27.0,40.0,31.0,30.5,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Drew Eubanks,C,6'9,245,1997-02-01,6,27.0,37.0,4.0,15.4,...,0.632,1.1,3.5,4.5,1.2,0.3,0.9,0.8,1.2,5.8
4,Kyle Filipowski,C,6'11,250,2003-11-07,R,21.0,72.0,27.0,21.1,...,0.650,1.6,4.6,6.1,1.9,0.7,0.3,1.4,2.4,9.6

### Example for NaN values: Here i'm inserting missing data for Jaden Springer

In [ ]:
df.loc[df['Player'] == 'Jaden Springer', 
       ['G','MP','FG','FGA','FG%','3P','3PA','3P%','2P','2PA','2P%','eFG%','FT','FTA','FT%','ORB','DRB','TRB','AST','STL','BLK','TOV','PF','PTS']] = [
    17,13.2,1.4,3.3,.411,0.4,1.7,.207,1.0,1.6,.630,.464,0.7,1.0,.706,0.8,1.2,2.0,1.4,0.7,0.2,0.7,1.5,3.8]

In [ ]:
df.loc[df['Player'] == 'Jaden Springer', ['Age', 'GS']] = [22, 0]

### Moving the "Age" column near the "Birth_Date" column

In [ ]:
col = df.pop("Age")
df.insert(5, "Age", col)

In [ ]:
df["Age"] = df["Age"].astype(int)

### Changing values type

In [ ]:
df["G"] = df["G"].astype(int)
df["GS"] = df["GS"].astype(int)

In [ ]:
df.head()

,Player,Pos,Height,Weight,Birth_Date,Age,Exp,G,GS,MP,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Jordan Clarkson,SG,6'3,194,1992-06-07,32,10,37,9,26.0,...,0.797,0.7,2.5,3.2,3.7,0.8,0.2,2.3,1.4,16.2
1,Isaiah Collier,PG,6'3,210,2004-10-08,20,R,71,46,25.9,...,0.682,0.5,2.9,3.3,6.3,0.9,0.2,2.9,2.1,8.7
2,John Collins,PF,6'9,235,1997-09-23,27,7,40,31,30.5,...,0.848,2.2,6.0,8.2,2.0,1.0,1.0,2.6,2.9,19.0
3,Drew Eubanks,C,6'9,245,1997-02-01,27,6,37,4,15.4,...,0.632,1.1,3.5,4.5,1.2,0.3,0.9,0.8,1.2,5.8
4,Kyle Filipowski,C,6'11,250,2003-11-07,21,R,72,27,21.1,...,0.650,1.6,4.6,6.1,1.9,0.7,0.3,1.4,2.4,9.6

### Saving the dataset

In [ ]:
df.to_csv("UtahJazz24-25clean.csv", index=False)